defaults: &defaults
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  username: developer
  password:
  template: template0

development:
  <<: *defaults
  database: pong_development

test:
  <<: *defaults
  database: pong_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: developer
  password:
  min_messages: warning
  database: pong_production
